INSERT INTO exercise (name, muscle_group) VALUES
  -- Chest (40)
  ('Barbell Bench Press', 'Chest'),
  ('Incline Barbell Bench Press', 'Chest'),
  ('Decline Barbell Bench Press', 'Chest'),
  ('Flat Dumbbell Press', 'Chest'),
  ('Incline Dumbbell Press', 'Chest'),
  ('Decline Dumbbell Press', 'Chest'),
  ('Push-ups', 'Chest'),
  ('Weighted Push-ups', 'Chest'),
  ('Deficit Push-ups', 'Chest'),
  ('Incline Push-ups', 'Chest'),
  ('Decline Push-ups', 'Chest'),
  ('Plyometric Push-ups', 'Chest'),
  ('Band-Resisted Push-ups', 'Chest'),
  ('Cable Crossover', 'Chest'),
  ('High-to-Low Cable Crossover', 'Chest'),
  ('Low-to-High Cable Crossover', 'Chest'),
  ('Single Arm Cable Crossover', 'Chest'),
  ('Pec Deck Machine', 'Chest'),
  ('Flat Dumbbell Flyes', 'Chest'),
  ('Incline Dumbbell Flyes', 'Chest'),
  ('Machine Chest Press', 'Chest'),
  ('Incline Machine Chest Press', 'Chest'),
  ('Dips (Chest Focus)', 'Chest'),
  ('Dumbbell Pullover', 'Chest'),
  ('Barbell Pullover', 'Chest'),
  ('Cable Pullover', 'Chest'),
  ('Smith Machine Bench Press', 'Chest'),
  ('Floor Press', 'Chest'),
  ('Hex Press', 'Chest'),
  ('Svend Press', 'Chest'),
  ('Spoto Press', 'Chest'),
  ('Guillotine Press', 'Chest'),
  ('Single Arm Dumbbell Press', 'Chest'),
  ('Squeeze Press', 'Chest'),
  ('Wide Grip Bench Press', 'Chest'),
  ('Reverse Grip Bench Press', 'Chest'),
  ('Band-Resisted Bench Press', 'Chest'),
  ('Chains Bench Press', 'Chest'),
  ('Machine Fly', 'Chest'),
  ('Decline Cable Crossover', 'Chest'),

  -- Back (40)
  ('Deadlift', 'Back'),
  ('Trap Bar Deadlift', 'Back'),
  ('Deficit Deadlift', 'Back'),
  ('Block Pulls', 'Back'),
  ('Barbell Row', 'Back'),
  ('Pendlay Row', 'Back'),
  ('T-Bar Row', 'Back'),
  ('Pull-ups', 'Back'),
  ('Weighted Pull-ups', 'Back'),
  ('Wide Grip Pull-ups', 'Back'),
  ('Neutral Grip Pull-ups', 'Back'),
  ('Assisted Pull-ups', 'Back'),
  ('Chin-ups', 'Back'),
  ('Assisted Chin-ups', 'Back'),
  ('Lat Pulldown', 'Back'),
  ('Reverse Grip Lat Pulldown', 'Back'),
  ('V-Bar Pulldown', 'Back'),
  ('Single Arm Cable Lat Pulldown', 'Back'),
  ('Kneeling Cable Pulldown', 'Back'),
  ('Machine Pulldown', 'Back'),
  ('Seated Cable Row', 'Back'),
  ('Single Arm Dumbbell Row', 'Back'),
  ('Chest-Supported Dumbbell Row', 'Back'),
  ('Machine Row', 'Back'),
  ('Straight Arm Pulldown', 'Back'),
  ('Rack Pulls', 'Back'),
  ('Inverted Row', 'Back'),
  ('Kroc Row', 'Back'),
  ('Seal Row', 'Back'),
  ('Underhand Cable Row', 'Back'),
  ('Dual Cable Row', 'Back'),
  ('Renegade Row', 'Back'),
  ('Landmine Row', 'Back'),
  ('Cable Shrugs', 'Back'),
  ('Reverse Hyper', 'Back'),
  ('Back Extension', 'Back'),
  ('Single Arm Cable Row', 'Back'),
  ('Meadows Row', 'Back'),
  ('Good Mornings', 'Back'),
  ('Dumbbell Pullover (Back Focus)', 'Back'),

  -- Shoulders (40)
  ('Overhead Press (Barbell)', 'Shoulders'),
  ('Seated Barbell Press', 'Shoulders'),
  ('Seated Dumbbell Press', 'Shoulders'),
  ('Arnold Press', 'Shoulders'),
  ('Push Press', 'Shoulders'),
  ('Z-Press', 'Shoulders'),
  ('Bradford Press', 'Shoulders'),
  ('Cuban Press', 'Shoulders'),
  ('Single Arm Dumbbell Shoulder Press', 'Shoulders'),
  ('Single Arm Kettlebell Press', 'Shoulders'),
  ('Lateral Raise (Dumbbell)', 'Shoulders'),
  ('Leaning Dumbbell Lateral Raise', 'Shoulders'),
  ('Cable Lateral Raise', 'Shoulders'),
  ('Single Arm Cable Lateral Raise', 'Shoulders'),
  ('Machine Lateral Raise', 'Shoulders'),
  ('Front Raise (Barbell)', 'Shoulders'),
  ('Front Raise (Dumbbell)', 'Shoulders'),
  ('Alternating Dumbbell Front Raise', 'Shoulders'),
  ('Front Raise (Cable)', 'Shoulders'),
  ('Plate Front Raise', 'Shoulders'),
  ('Y-Raise (Dumbbell)', 'Shoulders'),
  ('Y-Raise (Cable)', 'Shoulders'),
  ('Face Pull', 'Shoulders'),
  ('Reverse Pec Deck', 'Shoulders'),
  ('Dumbbell Rear Delt Fly', 'Shoulders'),
  ('Seated Dumbbell Rear Delt Fly', 'Shoulders'),
  ('Bent Over Rear Delt Raise', 'Shoulders'),
  ('Single Arm Cable Rear Delt Fly', 'Shoulders'),
  ('Lying Rear Delt Raise', 'Shoulders'),
  ('Upright Row (Barbell)', 'Shoulders'),
  ('Upright Row (Cable)', 'Shoulders'),
  ('Barbell Shrugs', 'Shoulders'),
  ('Dumbbell Shrugs', 'Shoulders'),
  ('Trap Bar Shrugs', 'Shoulders'),
  ('Single Arm Dumbbell Shrug', 'Shoulders'),
  ('High Pull', 'Shoulders'),
  ('Smith Machine Overhead Press', 'Shoulders'),
  ('Machine Shoulder Press', 'Shoulders'),
  ('Landmine Press', 'Shoulders'),
  ('Lu Raise', 'Shoulders'),

  -- Legs (40)
  ('Barbell Squat', 'Legs'),
  ('Front Squat', 'Legs'),
  ('Box Squat', 'Legs'),
  ('Zercher Squat', 'Legs'),
  ('Overhead Squat', 'Legs'),
  ('Goblet Squat', 'Legs'),
  ('Hack Squat', 'Legs'),
  ('Sissy Squat', 'Legs'),
  ('Pistol Squat', 'Legs'),
  ('Belt Squat', 'Legs'),
  ('Landmine Squat', 'Legs'),
  ('Leg Press', 'Legs'),
  ('Single Leg Press', 'Legs'),
  ('Romanian Deadlift (Barbell)', 'Legs'),
  ('Romanian Deadlift (Dumbbell)', 'Legs'),
  ('Stiff-Legged Deadlift', 'Legs'),
  ('Sumo Deadlift', 'Legs'),
  ('Trap Bar RDL', 'Legs'),
  ('B-Stance RDL', 'Legs'),
  ('Walking Lunges', 'Legs'),
  ('Reverse Lunges', 'Legs'),
  ('Forward Lunges', 'Legs'),
  ('Lateral Lunges', 'Legs'),
  ('Curtsy Lunges', 'Legs'),
  ('Bulgarian Split Squat', 'Legs'),
  ('Step-Ups', 'Legs'),
  ('Leg Extension', 'Legs'),
  ('Single Leg Extension', 'Legs'),
  ('Lying Hamstring Curl', 'Legs'),
  ('Seated Hamstring Curl', 'Legs'),
  ('Standing Leg Curl', 'Legs'),
  ('Standing Calf Raise', 'Legs'),
  ('Seated Calf Raise', 'Legs'),
  ('Leg Press Calf Raise', 'Legs'),
  ('Single Leg Calf Raise', 'Legs'),
  ('Glute Bridge', 'Legs'),
  ('Hip Thrust', 'Legs'),
  ('Cable Pull-Through', 'Legs'),
  ('Cable Kickbacks', 'Legs'),
  ('Hip Abductor Machine', 'Legs'),

  -- Biceps (40)
  ('Barbell Curl', 'Biceps'),
  ('Wide Grip Barbell Curl', 'Biceps'),
  ('Close Grip Barbell Curl', 'Biceps'),
  ('EZ-Bar Curl', 'Biceps'),
  ('Reverse EZ-Bar Curl', 'Biceps'),
  ('Dumbbell Curl', 'Biceps'),
  ('Alternating Dumbbell Curl', 'Biceps'),
  ('Seated Alternating Dumbbell Curl', 'Biceps'),
  ('Seated Supinated Dumbbell Curl', 'Biceps'),
  ('Hammer Curl (Dumbbell)', 'Biceps'),
  ('Incline Hammer Curl', 'Biceps'),
  ('Cross Body Hammer Curl', 'Biceps'),
  ('Cable Hammer Curl', 'Biceps'),
  ('Preacher Curl (Barbell)', 'Biceps'),
  ('Preacher Curl (Dumbbell)', 'Biceps'),
  ('Single Arm Preacher Curl (Dumbbell)', 'Biceps'),
  ('Preacher Curl (Machine)', 'Biceps'),
  ('Incline Dumbbell Curl', 'Biceps'),
  ('Concentration Curl', 'Biceps'),
  ('Spider Curl', 'Biceps'),
  ('Cable Bicep Curl', 'Biceps'),
  ('Single Arm Cable Curl', 'Biceps'),
  ('Behind-the-Back Cable Curl', 'Biceps'),
  ('Lying Cable Curl', 'Biceps'),
  ('Dual High Cable Curl', 'Biceps'),
  ('High Cable Curl', 'Biceps'),
  ('Cable Rope Curl', 'Biceps'),
  ('Reverse Curl (Barbell)', 'Biceps'),
  ('Reverse Dumbbell Curl', 'Biceps'),
  ('Zottman Curl', 'Biceps'),
  ('Drag Curl', 'Biceps'),
  ('Waiter Curl', 'Biceps'),
  ('Machine Bicep Curl', 'Biceps'),
  ('Banded Bicep Curl', 'Biceps'),
  ('Bayesian Curl', 'Biceps'),
  ('Strict Wall Curl', 'Biceps'),
  ('Cheat Curl', 'Biceps'),
  ('Suspension Trainer (TRX) Bicep Curl', 'Biceps'),
  ('Chin-up (Bicep Focus)', 'Biceps'),
  ('Reverse Grip Pulldown (Bicep Focus)', 'Biceps'),

  -- Triceps (40)
  ('Tricep Pushdown (Rope)', 'Triceps'),
  ('Tricep Pushdown (Straight Bar)', 'Triceps'),
  ('Tricep Pushdown (V-Bar)', 'Triceps'),
  ('Reverse Grip Tricep Pushdown', 'Triceps'),
  ('Single Arm Tricep Pushdown', 'Triceps'),
  ('Dual Cable Tricep Pushdown', 'Triceps'),
  ('Skullcrusher (EZ-Bar)', 'Triceps'),
  ('Skullcrusher (Dumbbell)', 'Triceps'),
  ('Decline Skullcrusher', 'Triceps'),
  ('Incline Skullcrusher', 'Triceps'),
  ('Close-Grip Bench Press', 'Triceps'),
  ('Floor Press (Close Grip)', 'Triceps'),
  ('Pin Press', 'Triceps'),
  ('Overhead Tricep Extension (Dumbbell)', 'Triceps'),
  ('Single Arm Overhead Dumbbell Extension', 'Triceps'),
  ('Overhead Tricep Extension (Cable)', 'Triceps'),
  ('Overhead Tricep Extension (EZ-Bar)', 'Triceps'),
  ('Seated French Press', 'Triceps'),
  ('Lying Dumbbell Tricep Extension', 'Triceps'),
  ('Cross-Body Tricep Extension', 'Triceps'),
  ('Tricep Kickback (Dumbbell)', 'Triceps'),
  ('Tricep Kickback (Cable)', 'Triceps'),
  ('Dips (Tricep Focus)', 'Triceps'),
  ('Weighted Dips', 'Triceps'),
  ('Bench Dips', 'Triceps'),
  ('Weighted Bench Dips', 'Triceps'),
  ('Machine Tricep Extension', 'Triceps'),
  ('Tate Press', 'Triceps'),
  ('JM Press', 'Triceps'),
  ('Rolling Dumbbell Tricep Extension', 'Triceps'),
  ('Single Arm Cable Pushdown', 'Triceps'),
  ('Single Arm Reverse Grip Pushdown', 'Triceps'),
  ('French Press', 'Triceps'),
  ('Diamond Push-ups', 'Triceps'),
  ('Close-Grip Push-up', 'Triceps'),
  ('Sphinx Push-up', 'Triceps'),
  ('Lying Tricep Extension (Cable)', 'Triceps'),
  ('Banded Tricep Extension', 'Triceps'),
  ('Cable Kickback', 'Triceps'),
  ('Bodyweight Tricep Extension', 'Triceps'),

  -- Core (40)
  ('Plank', 'Core'),
  ('Side Plank', 'Core'),
  ('Weighted Plank', 'Core'),
  ('Plank Jacks', 'Core'),
  ('Plank with Shoulder Taps', 'Core'),
  ('RKC Plank', 'Core'),
  ('Hanging Leg Raise', 'Core'),
  ('Hanging Knee Raise', 'Core'),
  ('Captain''s Chair Leg Raise', 'Core'),
  ('Lying Leg Raise', 'Core'),
  ('Cable Crunch', 'Core'),
  ('Decline Crunch', 'Core'),
  ('Machine Crunch', 'Core'),
  ('Reverse Crunch', 'Core'),
  ('Butterfly Crunch', 'Core'),
  ('Swiss Ball Crunch', 'Core'),
  ('Ab Wheel Rollout', 'Core'),
  ('Barbell Rollout', 'Core'),
  ('Russian Twist', 'Core'),
  ('Weighted Russian Twist', 'Core'),
  ('Bicycle Crunches', 'Core'),
  ('V-Ups', 'Core'),
  ('Dead Bug', 'Core'),
  ('Hollow Body Hold', 'Core'),
  ('L-Sit', 'Core'),
  ('V-Sit Hold', 'Core'),
  ('Dragon Flag', 'Core'),
  ('Woodchoppers', 'Core'),
  ('Cable Woodchopper (High to Low)', 'Core'),
  ('Cable Woodchopper (Low to High)', 'Core'),
  ('Landmine Twist', 'Core'),
  ('Windshield Wipers', 'Core'),
  ('Flutter Kicks', 'Core'),
  ('Alternating Heel Touches', 'Core'),
  ('Toe Touches', 'Core'),
  ('Sit-ups', 'Core'),
  ('Bird Dog', 'Core'),
  ('Superman Hold', 'Core'),
  ('TRX Suspended Crunch', 'Core'),
  ('Pallof Press', 'Core');